#include <gtest/gtest.h>

#include <pqc/aes.h>
#include <pqc/falcon.h>
#include <pqc/mceliece.h>


#define TEST_SIZE(type, cipher, len) EXPECT_EQ(PQC_get_length(cipher, type), len);

TEST(SIZE, ALL)
{
    TEST_SIZE(PQC_LENGTH_SYMMETRIC, PQC_CIPHER_AES, PQC_AES_KEYLEN);

    TEST_SIZE(PQC_LENGTH_IV, PQC_CIPHER_AES, PQC_AES_IVLEN);

    TEST_SIZE(PQC_LENGTH_PUBLIC, PQC_CIPHER_MCELIECE, PQC_MCELIECE_PUBLIC_KEYLEN);
    TEST_SIZE(PQC_LENGTH_PRIVATE, PQC_CIPHER_MCELIECE, PQC_MCELIECE_PRIVATE_KEYLEN);
    TEST_SIZE(PQC_LENGTH_MESSAGE, PQC_CIPHER_MCELIECE, PQC_MCELIECE_MESSAGE_LENGTH);
    TEST_SIZE(PQC_LENGTH_SHARED, PQC_CIPHER_MCELIECE, PQC_MCELIECE_SHARED_LENGTH);

    TEST_SIZE(PQC_LENGTH_PUBLIC, PQC_CIPHER_FALCON, PQC_FALCON_PUBLIC_KEYLEN);
    TEST_SIZE(PQC_LENGTH_PRIVATE, PQC_CIPHER_FALCON, PQC_FALCON_PRIVATE_KEYLEN);
    TEST_SIZE(PQC_LENGTH_SIGNATURE, PQC_CIPHER_FALCON, PQC_FALCON_SIGNATURE_LEN);
}
