name: Docs

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Copy includes
      shell: bash
      run: |
        mkdir docs/_includes
        cp -R examples docs/_includes

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Build
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./docs
        destination: ./_site

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3

  deploy:
    if: github.event_name == 'push'

    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
